on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: '/samvera.org'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Build and deploy'
        uses: tsg-iitkgp/next-build-export-action@v1.1
        env:
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
